spring:
  application:
    name: grouter-be

  datasource:
    url: jdbc:postgresql://${DB_URL}/dummy?sslmode=disable
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
